<?php

namespace ShopBundle\Repository;

/**
 * DeliveryMethodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryMethodsRepository extends \Doctrine\ORM\EntityRepository
{
}
