<?php

namespace ShopBundle\Repository;

/**
 * DeliveryTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryTermsRepository extends \Doctrine\ORM\EntityRepository
{
}
