<?php

namespace ShopBundle\Repository;

/**
 * DiscountListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountListRepository extends \Doctrine\ORM\EntityRepository
{
}
