<?php

namespace ShopBundle\Repository;

/**
 * Group1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group1Repository extends \Doctrine\ORM\EntityRepository
{
    public function getNames() {
        $qb = $this->createQueryBuilder('g')
            ->select('g.itemgroup1')
            ->addSelect('g.id')

        ;

        return $qb->getQuery()->getResult();
    }
}
