<?php

namespace ShopBundle\Repository;

/**
 * Group4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group4Repository extends \Doctrine\ORM\EntityRepository
{
}
