<?php

namespace ShopBundle\Repository;

/**
 * Group5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group5Repository extends \Doctrine\ORM\EntityRepository
{
}
