<?php

namespace ShopBundle\Repository;

/**
 * ItemDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
