<?php

namespace ShopBundle\Repository;

/**
 * PriceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListRepository extends \Doctrine\ORM\EntityRepository
{
}
