imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@ShopBundle/Resources/config/services.yml' }
    - { resource: '@UserBundle/Resources/config/services.yml' }
    - { resource: '@PortalBundle/Resources/config/services.yml' }
    - { resource: '@WBBundle/Resources/config/services.yml' }
parameters:
    locale: en
framework:
    secret: '%secret%'
    router: { resource: '%kernel.project_dir%/app/config/routing.yml', strict_requirements: null }
    form: null
    csrf_protection: null
    validation: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: null
    templating: { engines: [twig] }
    session: { handler_id: session.handler.native_file, save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%' }
    fragments: null
    http_method_override: true
    assets: null
    php_errors: { log: true }
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
doctrine:
    dbal: { default_connection: default, connections: { default: { driver: pdo_pgsql, host: 192.168.100.136, port: 5432, dbname: shop_default, user: postgres, password: Nexti2018<, charset: UTF8 }, portal: { driver: pdo_pgsql, host: 192.168.100.136, port: 5432, dbname: portal, user: postgres, password: Nexti2018<, charset: UTF8 }, sh733: { driver: pdo_pgsql, host: 192.168.100.136, dbname: sh733, user: postgres, password: Nexti2018<, charset: UTF8 }, sh659: { driver: pdo_pgsql, host: 192.168.100.136, dbname: sh659, user: postgres, password: Nexti2018<, charset: UTF8 } } }
    orm: { default_entity_manager: default, entity_managers: { default: { connection: default, mappings: { WBBundle: null, UserBundle: null } }, portal: { connection: portal, mappings: { PortalBundle: null } }, sh733: { connection: sh733, mappings: { ShopBundle: null } }, sh659: { connection: sh659, mappings: { ShopBundle: null } } } }
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
sensio_framework_extra:
    router: { annotations: false }
