<?php

namespace PortalBundle\Repository;

/**
 * accountsystemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accountsystemsRepository extends \Doctrine\ORM\EntityRepository
{
}
