<?php

namespace PortalBundle\Repository;

/**
 * companyuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class companyuserRepository extends \Doctrine\ORM\EntityRepository
{
}
