<?php

namespace PortalBundle\Repository;

/**
 * DeviceSettingDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceSettingDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
