<?php

namespace PortalBundle\Repository;

/**
 * DeviceSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
