<?php

namespace PortalBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDeviceid($systemid) {
        $qb = $this->createQueryBuilder('u')
            ->leftJoin('u.userid', 'user')
            ->select('user.id')
            ->where('u.companyid = :systemid')

            ->setParameter(':systemid', $systemid)

        ;


        return $qb->getQuery()->getResult();
    }
}
