<?php

namespace PortalBundle\Repository;

/**
 * UserPortalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPortalRepository extends \Doctrine\ORM\EntityRepository
{
}
